### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by dineshv16425** [Mastering-Spring-MVC-4/mastering-spring-mvc4#1]
I am getting following build error.

FAILURE: Build failed with an exception.
10:01:56.158 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:56.159 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
10:01:56.159 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/home/dinesh/a/workspace/tmp/mastering-spring-mvc4/build.gradle' line: 18
10:01:56.159 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:56.160 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
10:01:56.160 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'mastering-spring-mvc4'.
10:01:56.160 [ERROR] [org.gradle.BuildExceptionReporter] > org/gradle/mvn3/org/apache/maven/model/building/ModelBuildingException
10:01:56.161 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:56.161 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
10:01:56.161 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
10:01:56.162 [LIFECYCLE] [org.gradle.BuildResultLogger] 
10:01:56.163 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

**Comment by geowarin** [comment]
Make sure to use the gradle wrapper (gradlew) to use the correct version of gradle
`./gradlew compileJava` works for me.
If you are on windows, `gradlew.bat compileJava`.

If this doesn't work please run the build with the --stacktrace option as suggested.

**Comment by yasin3061** [comment]
@dineshv16425 If the issue is resolved, can you please close it? If not, please provide the outcome of steps mentioned in the above comment.

**Comment by dineshv16425** [comment]
not facing this issue.
