### ISSUE TITLE
Missing picture upload functionality

### ISSUE THREAD

**Issue by jirehstudios** [Mastering-Spring-MVC-4/mastering-spring-mvc4#3]
See Chapter 4 of book.

**Comment by geowarin** [comment]
What do you mean?

The code is [here](https://github.com/Mastering-Spring-MVC-4/mastering-spring-mvc4/blob/master/src/main/java/masterSpringMvc/profile/PictureUploadController.java).

You can even checkout the [chapter 4 branch](https://github.com/Mastering-Spring-MVC-4/mastering-spring-mvc4/tree/chapter-4-upload) and you will be in the exact same state than in the checkpoint of the chapter 4.

If you look at the [commit history](https://github.com/Mastering-Spring-MVC-4/mastering-spring-mvc4/commits/chapter-4-upload) of this branch, you can even follow the progression of the chapter step by step.

**Comment by jirehstudios** [comment]
Well yeah but it's missing stuff. For example, getUploadedPicture() on that controller is using both HttpResponse and Path in the book. You only have HttpResponse here.

**Comment by jirehstudios** [comment]
Oh I see, it's removed further on? In that case ignore this issue.
